Depth argument is prome to failure for ansible<2.3
I sometimes get this error under ansible 2.1/2.2 during the
clone of each role:

``An exception occurred during task execution.
To see the full traceback, use -vvv.
The error was: AttributeError: 'AnsibleModule' object has no attribute
'warn'

failed: [localhost] (item=
{'name': u'apt_package_pinning',
 'scm': u'git', 'src': u'https://git.openstack.org/openstack/openstack-
    ansible-apt_package_pinning',
 'version': u'origin/stable/ocata'
}) =>{
"failed": true, "item": {
  "name": "apt_package_pinning", "scm": "git",
  "src": "https://git.openstack.org/openstack/openstack-ansible-
  apt_package_pinning", "version": "origin/stable/ocata"
 },
"module_stderr":
 "Traceback (most recent call last):
  File \"/tmp/ansible_Ukqz_Z/ansible_module_git.py\", line 1038,
  in <module> main()
  File \"/tmp/ansible_Ukqz_Z/ansible_module_git.py\", line 952, in main
  clone(git_path, module, repo, dest, remote, depth, version, bare,
   reference, refspec, verify_commit)
  File \"/tmp/ansible_Ukqz_Z/ansible_module_git.py\", line 391, in clone
  module.warn(\"Ignoring depth argument. \"
  AttributeError: 'AnsibleModule' object has no attribute 'warn'",
"module_stdout": "", "msg": "MODULE FAILURE"
}

An exception occurred during task execution. To see the full traceback,
use -vvv. The error was: AttributeError: 'AnsibleModule' object has no
attribute 'warn'
``

When commenting the depth argument, the issue is skipped.

Change-Id: I1deb22f536bcec24e0d4e3c6d49ed12010dd1f31
(cherry picked from commit 596b1b2af176a09a6636e7ffd3a8f7030fbc3eed)